services: # Define os serviços que serão rodados pelo Docker Compose
  db: # Nome do serviço
    image: postgres # Usa a imagem oficial do PostgreSQL do Docker Hub
    ports:
      - "5432:5432" # Mapeia a porta 5432 do host para a porta 5432 do container, assim permitindo acesso ao database a partir do host
    volumes:
      - pgdata:/var/lib/postgresql/data # Monta um volume nomeado 'pgdata' para ser persistir data nesse directorio dentro do container
    environment: # Define variáveis de ambiente para o container do PostgreSQL. Essas variáveis configuram o database PostgreSQL.
      - POSTGRES_DB=test_db # The name of the database to be created
      - POSTGRES_USER=postgres # The username for the PostgreSQL database
      - POSTGRES_PASSWORD=postgres # The password for the PostgreSQL database user

volumes: # Define um volume nomeado que poderá ser usado pelos serviços
  pgdata: # Volume nomeado 'pgdata' usado para persistir dados do PostgreSQL fora do container